# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-dynamic-grid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-dynamic-grid.yml down`
version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  node-docker:
    image: selenium/node-docker:4.1.2-20220208
    volumes:
      - ./assets:/opt/selenium/assets
      - ./config.toml:/opt/bin/config.toml
      - ./alllib:/libs
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - "SE_OPTS=--log-level INFO --tracing true"
      - "JAVA_OPTS=--javaagent:/libs/opentelemetry-javaagent-all.jar \
                    -Dotel.resource.attributes=service.name=node-chrome \
                    -Dotel.traces.exporter=jaeger \
                    -Dotel.exporter.jaeger.endpoint=http://localhost:6831	\
                    -Dotel.exporter.jaeger.timeout=10000"

  selenium-hub:
    image: selenium/hub:4.1.2-20220208
    container_name: selenium-hub
    volumes:
      - ./alllib:/libs/
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - "SE_OPTS=--log-level INFO --tracing true"
      - "JAVA_OPTS=-javaagent:/libs/opentelemetry-javaagent-all.jar \
                    -Dotel.resource.attributes=service.name=node-chrome \
                    -Dotel.traces.exporter=jaeger \
                    -Dotel.exporter.jaeger.endpoint=http://localhost:6831	\
                    -Dotel.exporter.jaeger.timeout=10000"
